replicaCount: 2

image:
  repository: juancorral/backend
  pullPolicy: IfNotPresent
  tag: "0.1.{{ .Chart.Version }}"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  name: ""
  automount: true 

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
    - host: roomscout.online
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: backend-backend-chart
              port:
                number: 8080
  tls: []

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

#livenessProbe:
 # httpGet:
 #   path: /api/names
  #  port: 8080
 # initialDelaySeconds: 5
 # periodSeconds: 10

#readinessProbe:
#  httpGet:
#    path: /api/names
#    port: 8080
#  initialDelaySeconds: 5
#  periodSeconds: 10

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75

nodeSelector: {}
tolerations: []
affinity: {}
