apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8demo-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: k8demo-db-sc  # You may need to create this StorageClass
  hostPath:
    path: /mnt/data  # Use a suitable directory or a cloud-managed storage solution