apiVersion: v1
kind: PersistentVolume
metadata:
  name: k8demo-db-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: do-block-storage  # Cambiado a StorageClass válida
  csi:
    driver: dobs.csi.digitalocean.com
    volumeHandle: k8demo-db-pv
